SET DATABASE SQL SYNTAX ORA TRUE;
/*
CREATE TABLE CLIENTES (
	ID NUMBER NOT NULL,
	NOME VARCHAR2(100) NOT NULL,
	CPF VARCHAR2(11) NOT NULL,
	FONE VARCHAR2(14),
	CONSTRAINT PK_CLIENTES_ID PRIMARY KEY (ID)
);*/